version: '3'

services:
  frontend:
    image: secure-flight-nextjs-image
    container_name: host-stack-frontend
    build:
      context: ./
      dockerfile: ./provision/development/Dockerfile
    ports:
      - ${NEXT_PUBLIC_APP_PORT}:3000
    stdin_open: true
    tty: true
    env_file:
      - .env
    networks:
      - main
    volumes:
      - ./:/home/app

networks:
  main:
    driver: bridge